### ISSUE TITLE
Not being able to run it to a device

### ISSUE THREAD

**Issue by rajudev** [WellTemperedFate/NFC_Ionic_app#1]
This line is causing me issues 
https://github.com/WellTemperedFate/NFC_Ionic_app/blob/d2a0015dbb25687e3eaee068111c0f99abcf5e52/src/pages/write/write.ts#L78

> $ionic cordova run android
? Looks like a fresh checkout! No ./node_modules directory found. Would you like to install project dependencies? Yes
Installing dependencies may take several minutes!
> npm i
✔ Running command - done!
✔ Creating ./www directory for you - done!
> cordova platform add android --save
Using cordova-fetch for cordova-android@~6.3.0
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms/android
        Package: io.ionic.starter
        Name: myNFCApp
        Activity: MainActivity
        Android target: android-26
Subproject Path: CordovaLib
Android project created with cordova-android@6.3.0
Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to the project
Installing "ionic-plugin-keyboard" for android
Adding ionic-plugin-keyboard to package.json
Saved plugin info for "ionic-plugin-keyboard" to config.xml
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android
               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
>Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
Installing "cordova-plugin-device" for android
Adding cordova-plugin-device to package.json
Saved plugin info for "cordova-plugin-device" to config.xml
Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for android
Adding cordova-plugin-splashscreen to package.json
Saved plugin info for "cordova-plugin-splashscreen" to config.xml
Discovered plugin "cordova-plugin-ionic-webview" in config.xml. Adding it to the project
Installing "cordova-plugin-ionic-webview" for android
Adding cordova-plugin-ionic-webview to package.json
Saved plugin info for "cordova-plugin-ionic-webview" to config.xml
Discovered plugin "phonegap-nfc" in config.xml. Adding it to the project
Installing "phonegap-nfc" for android
Adding phonegap-nfc to package.json
Saved plugin info for "phonegap-nfc" to config.xml
Discovered plugin "cordova-plugin-advanced-http" in config.xml. Adding it to the project
Installing "cordova-plugin-advanced-http" for android
Installing "cordova-plugin-file" for android
The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.
If this is a new application no changes are required.
If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:
      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"
to config.xml in order for the application to find previously stored files.
        
>Adding cordova-plugin-advanced-http to package.json
Saved plugin info for "cordova-plugin-advanced-http" to config.xml
--save flag or autosave detected
Saving android@~6.3.0 into config.xml file ...
Running app-scripts build: --platform android --target cordova
[18:21:40]  build dev started ... 
[18:21:40]  clean started ... 
[18:21:40]  clean finished in 1 ms 
[18:21:40]  copy started ... 
[18:21:41]  deeplinks started ... 
[18:21:41]  deeplinks finished in 42 ms 
[18:21:41]  transpile started ... 
[18:21:43]  typescript: src/pages/write/write.ts, line: 78 
            Expected 3 arguments, but got 1. 
      L78:    this.nfc.write(this.ndef.textRecord(this.input.toString()));
      L79:    this.writeReady = false;
Error: Failed to transpile program
    at new BuildError (/home/raju/dev/github.com/NFC_Ionic_app/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at /home/raju/dev/github.com/NFC_Ionic_app/node_modules/@ionic/app-scripts/dist/transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (/home/raju/dev/github.com/NFC_Ionic_app/node_modules/@ionic/app-scripts/dist/transpile.js:107:12)
    at Object.transpile (/home/raju/dev/github.com/NFC_Ionic_app/node_modules/@ionic/app-scripts/dist/transpile.js:64:12)
    at /home/raju/dev/github.com/NFC_Ionic_app/node_modules/@ionic/app-scripts/dist/build.js:109:82
    at <anonymous>
[18:21:44]  copy finished in 3.04 s

**Comment by WellTemperedFate** [comment]
hello! thank you for testing and pointing out this error to me, i changed it, so it should work properly now! If you find any more issues, feel free to contact me again :)

**Comment by rajudev** [comment]
Hey @WellTemperedFate Thanks for the updation. 
But it is still not working for me.
Please take a look at https://ghostbin.com/paste/e3pzg

I have adb installed. 
and the initial requirements for running an Ionic app are properly setup. 
Thanks for your support earlier. Hope you get this sorted as well. Mean while I am also trying to make it work, the problem is somewhere in src/pages/write/write.ts around line #59

**Comment by rajudev** [comment]
This was a line while deploying it. 
> [09:49:00] typescript: src/pages/write/write.ts, line: 59 Expected 3 arguments, but got 1. 

line #59 in write.ts was only supplying 1 argument while the  module was expecting 3 arguments. 
So I changed the library rule in @ionic-native/nfc to only expect one argument instead. 

>//textRecord(text: string, languageCode: string, id: number[] | string): NdefRecord;
>    textRecord(text: string): NdefRecord;

That made it work. 

However, I made a change in the library, instead of the source code, which is not the right way to do it. 
Could you check for line number #59 in write.ts and see if it can be implemented in a better way?
Thanks.

**Comment by WellTemperedFate** [comment]
Hello @rajudev , I think I have encountered topics on this issue aswell. There seem to be 2 different nfc libraries that are in use for this, both using about the same syntax. The strange thing is this works perfectly for me, and i do not get the error of 3 arguments needed. Therefor I think this might do the trick:
$ ionic cordova plugin add phonegap-nfc
$ npm install --save @ionic-native/nfc

Hope this works...

**Comment by rajudev** [comment]
![screenshot_20171228-062855](https://user-images.githubusercontent.com/2010120/34409799-24053264-ebf2-11e7-912b-ef3b2930adfb.png)

nope, I tried a fresh clone with your above steps. It is causing the same issue.

**Comment by WellTemperedFate** [comment]
So it is only this line of code, giving you issues? If you open the code with visual studio code, and you start typing the same line, does it give you the intellisense that you need 3 arguments? Because I have no idea why it says 3 arguments needed since i only need 1 argument (both in visual studio code and my compiler). So at this point I kinda ran out of ideas. I tried it on 2 other devices now and it seems to work just fine on those devices too, no errors :/. So could you please try this and tell me what it says? I really would like it to work for you too.

edit:
I have the same error too now, I am working to resolve it...

**Comment by WellTemperedFate** [comment]
I updated the code, and tried it, this should do the trick! Hope it works now. Keep me updated :)

**Comment by rajudev** [comment]
I cloned in a completely new directory. It worked. Thanks. 
Probably you should add this in the README

> cordova plugin add phonegap-nfc --save
> npm install --save
>ionic cordova run --device

Thanks a lot.
